Repository Dulce-Work-Schedule/2018.1-Dulce_User, pull requests merged in 2018-06, with the labels that each got.

#11 Inicial
  .travis.yml
  Client/Dockerfile
  Client/client_login.js
  Client/package.json
  Environments/Development/Client/Dockerfile
  Environments/Development/Server/Dockerfile
  Environments/Development/Variables/mongo.env
  Environments/Development/Variables/rabbitmq.env
  Environments/Development/build.yml
  Environments/Development/start-deps.yml
  Environments/Development/start-login.yml
  Environments/Production/Client/Dockerfile
  Environments/Production/Server/Dockerfile
  Environments/Production/build.yml
  Environments/Test/Client/Dockerfile
  Environments/Test/Server/Dockerfile
  Environments/Test/Variables/.keep
  Environments/Test/Variables/coveralls.env
  Environments/Test/build.yml
  Environments/Test/start-login.yml
  README.md
  Server/Dockerfile
  Server/_login.js
  Server/login.js
  Server/package.json
  Server/test/login.test.js
  docker-compose.yml
  guia_de_instalacao.md
  utils/deploy.sh
  utils/script_coveralls.sh
Labels: 0-DevOps, 1-Infraestrutura, 2-Deploy Contínuo, 4-Adicionado, 5-Avançado

#12 HOTFIX Atualizando deploy.sh
  utils/deploy.sh
Labels: 0-DevOps, 1-Infraestrutura, 2-Deploy Contínuo, 4-Débito Técnico, 5-Avançado

#14 Fix #13 Realizando correções necessárias
  Client/client_login.js
  Environments/Development/build.yml
  guia_de_instalacao.md
Labels: 0-DevOps, 1-Viabilidade Técnica, 4-Adicionado, 5-Iniciante

#18 Fix #17 refatorando campos de user
  Client/api.js
  Server/_user.js
  Server/test/user.test.js
Labels: 0-Developers, 1-Viabilidade Técnica, 2-Feature, 3-task, 4-Planejado, 5-Iniciante

#22 Fix #20 colocando validações para campos
  Client/api.js
Labels: 0-Developers, 1-Viabilidade Técnica, 2-Feature, 3-task, 4-Planejado, 5-Iniciante

#23 Fix #19 arrumando validação de email
  Client/api.js
  Server/_user.js
Labels: 0-Developers, 1-Viabilidade Técnica, 2-Feature, 3-task, 4-Planejado, 5-Iniciante

#24 HOTFIX 19 validar email
  Client/api.js
  Server/_user.js
Labels: 0-Developers, 1-Viabilidade Técnica, 3-task, 4-Planejado, 5-Iniciante

#27 Fix #21 validar email db
  Server/_user.js
  Server/package.json
  Server/test/user.test.js
Labels: 0-Developers, 1-Viabilidade Técnica, 2-Feature, 3-task, 4-Planejado, 5-Iniciante

#30 Fix #29 Corrigindo o edit user
  Client/api.js
  Server/_user.js
  Server/test/user.test.js
Labels: 0-Developers, 1-Viabilidade Técnica, 3-task, 4-Planejado, 5-Intermediário

#31 HOTFIX corrigindo erro de retorno
  Client/api.js
  Server/_user.js
Labels: BUG

#36 Fix #35 Modificando edit para não precisar de senha mais
  Client/api.js
  Server/_user.js
  Server/test/user.test.js
Labels: 0-Developers, 1-Produto, 3-task, 4-Adicionado, 5-Iniciante
